Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBankingApp.Data;
using WebBankingApp.Models;

namespace MVCWebBanking.Controllers
{
    public class AccountsController : Controller
    {
        private readonly BankingContext _context;

        public AccountsController(BankingContext context)
        {
            _context = context;
        }

        // GET: Accounts/Members
        public async Task<IActionResult> Members(int? id )
        {

            if (id == null)
            {
                return NotFound();
            }

            Account account = _context.Accounts
                .Include(x => x.Members)
                .ThenInclude(y => y.Member)
                .FirstOrDefault(a => a.Id == id);

            return View(account);
        }

        // Creates a cookie so that the current active account persists through each controller
        private void CreateAccountCookie(int accountId)
        {
            CookieOptions options = new CookieOptions
            {
                Domain = "localhost", // Set the domain for the cookie
                Expires = DateTime.Now.AddHours(1), // Set expiration date to 1 hour from now
                Path = "/", // Cookie is available within the entire application
                Secure = true, // Ensure the cookie is only sent over HTTPS
                HttpOnly = true, // Prevent client-side scripts from accessing the cookie
                IsEssential = true // Indicates the cookie is essential for the application to function
            };

            Response.Cookies.Append("accountId", accountId.ToString(), options);
        }

        // GET: Account/Login
        public IActionResult Login()
        {
            return View();
        }

        // POST: Account/Login
        // To protect fom overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Id")] Account account)
        {
            try
            {
                account = _context.Accounts.Single(a => a.Id == account.Id);

                CreateAccountCookie(account.Id);

                return RedirectToAction(nameof(Details), new { id = account.Id });
            }
            catch (InvalidOperationException ioe) 
            {
                ModelState.AddModelError("Id", "Login Failed");
            }     

            return View();
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details()
        {
            int id = Convert.ToInt32(Request.Cookies["accountId"]);

            if (id == null)
            {
                return NotFound();
            }

            var account =  _context.Accounts
                .Include(s => s.Shares)
                .FirstOrDefault(m => m.Id == id);

            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }
        
    }
}

Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBankingApp.Data;
using WebBankingApp.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace MVCWebBanking.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly BankingContext _context;

        public TransactionsController(BankingContext context)
        {
            _context = context;
        }

        // GET: Transactions/Deposit
        public IActionResult Deposit(int? shareId)
        {
            ViewData["shareId"] = shareId;
            return View();
        }

        // Helper function that checks to make sure input amounts are positive
        public bool VerifyAmountNonNegative(Transaction transaction)
        {
            if (transaction.Amount < 0)
            {
                ModelState.AddModelError("Amount", "Amount must be a positive value");
                return false;
            }

            return true;
        }

        // POST: Transactions/Deposit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deposit(int shareId, [Bind("Amount")] Transaction transaction)
        {
            ViewData["shareId"] = shareId;

            VerifyAmountNonNegative(transaction);

            // Loads share from database and performs deposit
            Share share = _context.Shares.Include(s => s.Account).Where(w => w.Id == shareId).Single();
            share.CurrentBalance += transaction.Amount;

            // Sets transaction values
            transaction.DateTime = DateTime.Now;
            transaction.Share = share;
            transaction.NewBalance = share.CurrentBalance;

            ModelState.ClearValidationState(nameof(Share));

            // Verify's share model is valid and saves changes to database if so,
            // if not, reload page
            if (TryValidateModel(transaction, nameof(Share)))
            {
                _context.Add(transaction);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Shares", new { id = shareId });
            }

            return View();
        }

        // GET: Transactions/Transfer
        public IActionResult Transfer(int? shareId)
        {
            ViewData["fromShareId"] = shareId;

            Share share;

            try
            {
                share = _context.Shares
                    .Include(a => a.Account)
                    .ThenInclude(s => s.Shares)
                    .Where(i => i.Id == shareId)
                    .Single();
            }
            catch (Exception InvalidOperation)
            {
                // If shares is null return to shares details page
                return RedirectToAction("Details", "Shares", new { id = shareId });
            }

            List<Share> shares = share.Account.Shares;

            // Removes the from share from the list of possible to shares
            shares.Remove(share);

            // If there is no other shares you cannot perform a transfer to other shares
            if (shares.Count == 0)
            {
                return RedirectToAction("Details", "Shares", new { id = shareId });
            }
                        
            ViewData["shares"] = shares;
            ViewData["fromShare"] = share;

            return View(new Transaction());
        }

        // POST: Transactions/Transfer
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Transfer(int fromShareId, int toShareId, [Bind("Amount")] Transaction transaction)
        {         
            // Set up view state in case of errors
            ViewData["fromShareId"] = fromShareId;
            Share share = _context.Shares
               .Include(a => a.Account)
               .ThenInclude(s => s.Shares)
               .Where(i => i.Id == fromShareId)
               .Single();
            List<Share> shares = share.Account.Shares;


            bool validAmount = VerifyAmountNonNegative(transaction);

            // Checks to see if a toShare was selected
            if (toShareId == 0)
            {
                shares.Remove(share);
                ViewData["shares"] = shares;
                ViewData["fromShare"] = share;
                ModelState.AddModelError("Amount", "Please select a share to transfer to.");
                return View();
            }

            transaction.DateTime = DateTime.Now;
            
            // Loads fromShare and toShare from database 
            Share fromShare = _context.Shares
                .Include(s => s.Account)
                .Where(w => w.Id == fromShareId)
                .Single();
            Share toShare = _context.Shares
                .Include(s => s.Account)
                .Where(w => w.Id == toShareId)
                .Single();

            // Verifies from share has the balance available to transfer
            if (fromShare.CurrentBalance - transaction.Amount >= fromShare.MinimumBalance)
            {
                fromShare.CurrentBalance -= transaction.Amount;
                toShare.CurrentBalance += transaction.Amount;
            }
            else
            {
                shares.Remove(share);
                ViewData["shares"] = shares;
                ViewData["fromShare"] = share;
                ModelState.AddModelError("Amount", "Insufficient Balance");
                return View();
            }          

            // Sets transaction values
            Transaction fromTransaction = new Transaction(transaction);
            Transaction toTransaction = new Transaction(transaction);

            ModelState.Remove("Share");
            ModelState.Remove("Amount");

            // Makes the amount on the fromShare report as a credit vs a debit
            fromTransaction.Amount = -1 * fromTransaction.Amount;        

            // Updates NewBalance on transactions
            fromTransaction.NewBalance = fromShare.CurrentBalance;
            toTransaction.NewBalance = toShare.CurrentBalance;

            fromShare.Transactions.Add(fromTransaction);
            toShare.Transactions.Add(toTransaction);


            // Validate transactions before save
            ValidationContext fromContext = new ValidationContext(fromTransaction);
            ValidationContext toContext = new ValidationContext(toTransaction);
            List<ValidationResult> results = new List<ValidationResult>();
            bool fromTransactionValid = Validator.TryValidateObject(fromTransaction, fromContext, results, true);
            bool toTransactionValid = Validator.TryValidateObject(toTransaction, toContext, results, true);

            if (validAmount)
            {
                if (fromTransactionValid && toTransactionValid)
                {
                    _context.SaveChanges();
                    return RedirectToAction("Details", "Shares", new { id = fromShareId });
                }
                else
                {
                    ModelState.AddModelError("Amount", "Transaction Not Valid");
                }
            }

            shares.Remove(share);
            ViewData["shares"] = shares;
            ViewData["fromShare"] = share;
            return View();
        }

        // GET: Transactions/ExternalTransfer
        public IActionResult ExternalTransfer(int? shareId)
        {
            ViewData["fromShareId"] = shareId;

            Share share;

            try
            {
                share = _context.Shares
                    .Include(a => a.Account)
                    .ThenInclude(s => s.Shares)
                    .Where(i => i.Id == shareId)
                    .Single();
            }
            catch (Exception InvalidOperation)
            {
                // If shares is null return to shares details page
                return RedirectToAction("Details", "Shares", new { id = shareId });
            }

            ViewData["fromShare"] = share;

            return View();
        }

        // POST: Transactions/Deposit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ExternalTransfer(int shareId, [Bind("Amount")] Transaction transaction)
        {
            ViewData["fromShareId"] = shareId;

            VerifyAmountNonNegative(transaction);

            // Loads share from database and performs deposit
            Share share = _context.Shares.Include(s => s.Account).Where(w => w.Id == shareId).Single();

            if (share.CurrentBalance - share.MinimumBalance >= transaction.Amount)
            {
                share.CurrentBalance -= transaction.Amount;
            }
            else
            {
                ModelState.AddModelError("Amount", "Insufficient Balance");
                return View();
            }

            // Sets transaction values
            transaction.DateTime = DateTime.Now;
            transaction.Share = share;
            transaction.NewBalance = share.CurrentBalance;
            transaction.Amount = -1 * transaction.Amount;

            ModelState.ClearValidationState(nameof(Share));

Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebBanking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebBanking.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="home" asp-action="index">MVC Web Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarsupportedcontent"
                        aria-expanded="false" aria-label="toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                   @*  <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="index">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="privacy">privacy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="shares" asp-action="index">shares</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="members" asp-action="index">members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="transactions" asp-action="index">transactions</a>
                        </li>
                    </ul> *@
                </div>
            </div>
        </nav> 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCWebBanking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebBanking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebBanking.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC Web Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Details" asp-route-id="@Context.Request.Cookies["accountId"]">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Members" asp-route-id="@Context.Request.Cookies["accountId"]">Members</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="MemberToMemberTransfer" asp-route-id="@Context.Request.Cookies["accountId"]">Member To Member Transfer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="ExternalTransfer" asp-route-id="@Context.Request.Cookies["accountId"]">External Transfer</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCWebBanking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>